"use client";
import { AppShell } from "@/components/app-shell";
import { useDemo } from "@/lib/demo-store";
import { Grid2X2, Rows3, Shapes } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { Classroom } from "@/lib/types";

export default function NewRoom(){const router=useRouter();const{createRoom}=useDemo();const[layout,setLayout]=useState<Classroom["layout"]>("ROWS");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const room=createRoom({name:String(f.get("name")),subject:String(f.get("subject")),count:Number(f.get("count")),layout});router.push(`/teacher/classrooms/${room.id}`)}return <AppShell title="สร้างห้อง" back="/teacher/dashboard"><main className="narrow-shell"><div className="page-heading"><div><p className="eyebrow">ห้องเรียนใหม่</p><h1>ตั้งค่าห้องและโต๊ะ</h1><p>แก้ตำแหน่งและสถานะโต๊ะเพิ่มเติมได้หลังสร้างห้อง</p></div></div><form className="panel form-stack" onSubmit={submit}><div className="form-grid"><label>ชื่อห้อง<input name="name" required maxLength={60} placeholder="เช่น ห้องทดลอง ม.2/1"/></label><label>ชื่อวิชา<input name="subject" required maxLength={80} placeholder="เช่น วิทยาศาสตร์ — การแยกสาร"/></label><label>จำนวนโต๊ะ<select name="count" defaultValue="12"><option value="8">8 โต๊ะ</option><option value="12">12 โต๊ะ</option><option value="16">16 โต๊ะ</option><option value="20">20 โต๊ะ</option></select></label></div><fieldset><legend>รูปแบบโต๊ะ</legend><div className="layout-choices">{[["ROWS","แถวปกติ",Rows3],["U_SHAPE","รูปตัว U",Shapes],["GROUPS","แบบกลุ่ม",Grid2X2]].map(([value,label,Icon])=><button type="button" key={String(value)} className={layout===value?"active":""} onClick={()=>setLayout(value as Classroom["layout"])}><Icon size={26}/><strong>{String(label)}</strong></button>)}</div></fieldset><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>router.back()}>ยกเลิก</button><button className="primary-button" type="submit">สร้างและเปิดห้อง</button></div></form></main></AppShell>}
