"use client";
import { AppShell, LoadingState } from "@/components/app-shell";
import { TeacherProfileBadge } from "@/components/teacher-profile-form";
import { useDemo } from "@/lib/demo-store";
import { BarChart3, ChevronRight, CirclePlus, Clock3, DoorOpen, UsersRound } from "lucide-react";
import { useRouter } from "next/navigation";

export default function Dashboard(){
  const store=useDemo();const router=useRouter();
  if(!store.ready)return <AppShell title="แดชบอร์ดครู"><LoadingState/></AppShell>;
  const rooms=store.rooms.filter(room=>store.canManage(room.id));
  return <AppShell title="แดชบอร์ดครู"><main className="dashboard-shell"><div className="page-heading"><div><p className="eyebrow">ภาพรวมห้องเรียน</p><h1>สวัสดี{store.profile?` ครู${store.profile.nickname}`:"คุณครู"}</h1><p>เลือกห้องเดิมหรือสร้างห้องใหม่เพื่อเริ่มกิจกรรม</p></div><div className="teacher-heading-actions">{store.profile&&<button className="teacher-profile-link" onClick={()=>router.push("/teacher/profile")}><TeacherProfileBadge profile={store.profile}/><span>แก้ไขโปรไฟล์</span></button>}<button className="primary-button compact" onClick={()=>router.push("/teacher/classrooms/new")}><CirclePlus size={20}/>สร้างห้องใหม่</button></div></div><section className="stats-row"><article><span><DoorOpen/></span><div><strong>{rooms.filter(r=>r.status!=="ENDED").length}</strong><small>ห้องที่เปิดอยู่</small></div></article><article><span><UsersRound/></span><div><strong>{rooms.reduce((n,r)=>n+r.students.length,0)}</strong><small>นักเรียนทั้งหมด</small></div></article><article><span><BarChart3/></span><div><strong>{rooms.reduce((n,r)=>n+r.students.reduce((x,s)=>x+s.totalScore,0),0)}</strong><small>คะแนนรวม</small></div></article></section><div className="section-title"><h2>ห้องเรียนของฉัน</h2><span>{rooms.length} ห้อง</span></div><section className="room-list">{rooms.length?rooms.map(room=><button className="room-row" key={room.id} onClick={()=>router.push(`/teacher/classrooms/${room.id}`)}><span className={`status-dot ${room.status.toLowerCase()}`}/><span className="room-main"><strong>{room.name}</strong><small>{room.subject}</small></span><span className="room-meta"><span><UsersRound size={16}/>{room.students.length} คน</span><span><Clock3 size={16}/>{room.status==="OPEN"?"เปิดรับนักเรียน":room.status==="RUNNING"?"กำลังทดลอง":room.status==="PAUSED"?"หยุดชั่วคราว":"จบแล้ว"}</span></span><code>{room.code}</code><ChevronRight/></button>):<div className="mini-empty"><DoorOpen/><strong>ยังไม่มีห้องเรียน</strong><span>สร้างห้องใหม่เพื่อเริ่มออกโจทย์และแชร์ QR</span></div>}</section></main></AppShell>;
}
