"use client";

import { AppShell, LoadingState } from "@/components/app-shell";
import { ActivityConfigDialog, RoomQrDialog } from "@/components/classroom-dialogs";
import { DeskGrid } from "@/components/desk-grid";
import { GameStartCountdown, useGameClock } from "@/components/game-start-countdown";
import { useDemo } from "@/lib/demo-store";
import { finishedLevels, rankedStudents } from "@/lib/live-game";
import { CirclePause, CirclePlay, CirclePlus, Copy, Download, Hand, LockKeyhole, QrCode, Settings2, Share2, Square, Unlock, Users, Trophy, ChartNoAxesColumnIncreasing, Flag, FlaskConical, Check, X } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function TeacherRoom(){
  const {id}=useParams<{id:string}>();
  const store=useDemo();
  const router=useRouter();
  const [notice,setNotice]=useState("");
  const [pending,setPending]=useState(false);
  const [noticeError,setNoticeError]=useState(false);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),4500);return()=>clearTimeout(timer)},[notice]);
  const [qrOpen,setQrOpen]=useState(false);
  const [configOpen,setConfigOpen]=useState(false);
  const room=store.rooms.find(r=>r.id===id);
  const now=useGameClock(room);
  if(!store.ready)return <AppShell title="ห้องเรียนสด"><LoadingState/></AppShell>;
  if(!room)return <AppShell title="ห้องเรียนสด"><main className="empty-state"><h1>ไม่พบห้องเรียน</h1><button className="primary-button" onClick={()=>router.push("/teacher/dashboard")}>กลับแดชบอร์ด</button></main></AppShell>;
  const joinUrl=`${typeof location!=="undefined"?location.origin:""}/join/${room.code}`;
  async function copy(value:string,message:string){try{await navigator.clipboard.writeText(value);setNoticeError(false);setNotice(message)}catch{setNoticeError(true);setNotice("คัดลอกไม่สำเร็จ กรุณาลองอีกครั้ง")}}
  async function share(){if(!room)return;try{if(navigator.share){await navigator.share({title:`เข้าห้อง ${room.name}`,text:`เข้าห้อง ChemClass Lab รหัส ${room.code}`,url:joinUrl});return;}await copy(joinUrl,"คัดลอกลิงก์เข้าห้องแล้ว")}catch(error){if(error instanceof Error&&error.name==="AbortError")return;setNoticeError(true);setNotice("แชร์ลิงก์ไม่สำเร็จ กรุณาลองอีกครั้ง")}}
  function manage(action:Promise<void>){setPending(true);setNoticeError(false);void action.catch(e=>{setNoticeError(true);setNotice(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}).finally(()=>setPending(false))}
  function end(){if(room&&confirm("ยืนยันจบห้อง? นักเรียนจะส่งคำตอบเพิ่มไม่ได้"))manage(store.setRoomStatus(room.id,"ENDED"))}
  const maxScore=room.activity.levelIds.reduce((sum,levelId)=>sum+(room.activity.pointsByLevel[levelId]??5),0);
  const shared=store.canManage(room.id);
  const ranked=rankedStudents(room.students);
  const totalLevels=room.activity.levelIds.length;
  const finished=room.students.filter(student=>finishedLevels(student,room.activity.levelIds)).length;
  const average=room.students.length?Math.round(room.students.reduce((sum,student)=>sum+student.totalScore,0)/room.students.length):0;
  const statusLabel=room.status==="RUNNING"?"กำลังทดลอง":room.status==="PAUSED"?"หยุดชั่วคราว":room.status==="ENDED"?"จบแล้ว":"นักเรียนกำลังรอเริ่ม";

  return <AppShell compact title="ห้องเรียนสด" back="/teacher/dashboard"><main className="classroom-shell teacher-live">
    <section className="room-top"><div className="classroom-info"><div className="classroom-heading-meta"><p className="eyebrow">ห้องเรียนสด</p><span className={"session-badge "+room.status.toLowerCase()}><i aria-hidden="true"/>{room.status==="RUNNING"&&"LIVE · "}{statusLabel}</span></div><h1>{room.name}</h1><p>{room.subject}</p><div className="classroom-meta"><span><Users size={16}/>{room.students.length} ผู้เข้าร่วม</span><span><FlaskConical size={16}/>{totalLevels} ข้อ</span></div></div><div className="room-code-card"><span>รหัสห้อง</span><strong>{room.code}</strong><div className="room-access-actions"><button disabled={!shared} onClick={()=>void copy(room.code,"คัดลอกรหัสห้องแล้ว")} aria-label="คัดลอกรหัส" title="คัดลอกรหัส"><Copy size={18}/></button><button className="share-button" disabled={!shared} onClick={()=>void share()} aria-label="แชร์ลิงก์" title="แชร์ลิงก์"><Share2 size={18}/></button><button className="qr-button" disabled={!shared} onClick={()=>setQrOpen(true)}><QrCode size={19}/>แสดง QR</button></div></div></section>
    {!shared&&<div className="error-box" role="alert">ห้องนี้สร้างด้วยระบบเก่าที่เก็บเฉพาะเครื่องครู มือถือจะเข้าไม่ได้ กรุณา <Link href="/teacher/classrooms/new">สร้างห้องใหม่</Link> แล้วแชร์ QR ใหม่</div>}{store.error&&<div className="error-box" role="alert">เผยแพร่ห้องไม่สำเร็จ: {store.error}</div>}{notice&&<div className={"classroom-toast "+(noticeError?"is-error":"")} role={noticeError?"alert":"status"}>{!noticeError&&<Check size={18}/>}<span>{notice}</span><button aria-label="ปิดข้อความ" onClick={()=>setNotice("")}><X size={18}/></button></div>}
    <div className="session-panel"><section className="activity-plan panel"><div className="selected-game-copy"><span className="game-icon"><FlaskConical size={25}/></span><div><span className="activity-kicker">เกมที่เลือก <span className="game-readiness">{totalLevels?room.status==="OPEN"?"พร้อมใช้งาน":statusLabel:"ยังไม่ได้เลือกเกม"}</span></span><strong>{room.activity.title||"เลือกชุดด่านเพื่อเริ่มกิจกรรม"}</strong><small>{room.activity.mode==="PRESET"?"ชุดมาตรฐาน":room.activity.mode==="QUESTIONS"?"โจทย์ที่ครูสร้าง":"เลือกด่านเอง"} · {room.activity.levelIds.length} ข้อ · {maxScore} คะแนน · {room.activity.hintsEnabled?"มีคำใบ้":"ปิดคำใบ้"}</small></div></div><div className="activity-plan-actions"><button className="secondary-button" disabled={!shared||room.status!=="OPEN"} onClick={()=>setConfigOpen(true)}><Settings2/>เลือกชุดด่าน</button><button className="secondary-button" disabled={!shared||room.status!=="OPEN"} onClick={()=>router.push(`/teacher/classrooms/${room.id}/questions`)}><CirclePlus/>สร้างโจทย์เอง</button></div></section>
    <section className="control-bar"><div className="activity-state"><span className={`status-dot ${room.status.toLowerCase()}`}/><div><small>สถานะกิจกรรม</small><strong>{room.status==="RUNNING"?"กำลังทดลอง":room.status==="PAUSED"?"หยุดชั่วคราว":room.status==="ENDED"?"จบแล้ว":"นักเรียนกำลังรอเริ่ม"}</strong></div></div><div className="control-actions" aria-busy={pending}>{pending&&<span className="session-pending" role="status">กำลังบันทึก…</span>}{room.status!=="RUNNING"&&room.status!=="ENDED"&&<button className="primary-button compact" disabled={pending||!shared||!totalLevels} onClick={()=>manage(store.setRoomStatus(room.id,"RUNNING"))}><CirclePlay/>{room.status==="PAUSED"?"ทำต่อ":"เริ่มเกม"}</button>}{room.status==="RUNNING"&&<button className="secondary-button" disabled={pending||!shared} onClick={()=>manage(store.setRoomStatus(room.id,"PAUSED"))}><CirclePause/>หยุดชั่วคราว</button>}<button className="danger-button" onClick={end} disabled={pending||!shared||room.status==="ENDED"}><Square/>จบห้อง</button></div></section></div>
    <section className="live-board panel" aria-label="คะแนนสดและอันดับนักเรียน"><div className="section-title"><div><p className="eyebrow">ผลการแข่งขันสด</p><h2>กระดานคะแนน</h2><span>อัปเดตคะแนนและความคืบหน้าอัตโนมัติ</span></div><div className="board-actions">{room.status==="RUNNING"&&<span className="board-live"><i aria-hidden="true"/>อัปเดตสด</span>}<button onClick={()=>router.push(`/teacher/classrooms/${room.id}/report`)}><Download/>สรุปผล / CSV</button></div></div><div className="live-summary"><div><Users aria-hidden="true"/><strong>{room.students.length}</strong><span>ผู้เข้าร่วม</span></div><div><Flag aria-hidden="true"/><strong>{finished}</strong><span>จบทุกด่าน</span></div><div><ChartNoAxesColumnIncreasing aria-hidden="true"/><strong>{average}</strong><span>คะแนนเฉลี่ย</span></div><div><Trophy aria-hidden="true"/><strong>{maxScore}</strong><span>คะแนนเต็ม</span></div></div>{ranked.length?<ol className="leaderboard">{ranked.map((student,index)=><li key={student.id}><span className="rank-number" aria-label={"อันดับ "+(index+1)}>{index===0?<Trophy size={18}/>:index+1}</span><div className="leader-name"><strong>{student.nickname}</strong><small>โต๊ะ {room.desks.find(d=>d.id===student.deskId)?.label??"ยังไม่เลือก"} · ผ่าน {student.completed.length} · ข้าม {student.skipped?.length??0} / {totalLevels} ข้อ {finishedLevels(student,room.activity.levelIds)?"· จบแล้ว":"· กำลังเล่น"}</small></div><div className="leader-progress"><span>{room.activity.levelIds.filter(id=>student.completed.includes(id)||student.skipped?.includes(id)).length} / {totalLevels}</span><progress aria-label={"ความคืบหน้า "+student.nickname} max={totalLevels||1} value={room.activity.levelIds.filter(id=>student.completed.includes(id)||student.skipped?.includes(id)).length}/></div>{student.handRaised&&<span className="hand-badge"><Hand/>ยกมือ</span>}<strong className="leader-score">{student.totalScore}<small>คะแนน</small></strong></li>)}</ol>:<div className="mini-empty"><QrCode/><strong>ยังไม่มีนักเรียน</strong><span>แชร์ QR เพื่อให้นักเรียนเข้าร่วม</span><button className="secondary-button" disabled={!shared} onClick={()=>setQrOpen(true)}><QrCode size={18}/>แสดง QR · {room.code}</button></div>}</section>
    <div className="teacher-layout"><section className="panel room-map"><div className="section-title"><div><h2>ผังห้องเรียน</h2><span>เห็นชื่อ ตำแหน่งที่นั่ง และนักเรียนที่ยกมือได้ทันที (คลิกนักเรียนเพื่อย้ายโต๊ะ)</span></div><div className="inline-actions"><button onClick={()=>manage(store.setAllLocks(room.id,true))}><LockKeyhole/>ล็อกทั้งหมด</button><button onClick={()=>manage(store.setAllLocks(room.id,false))}><Unlock/>ปลดทั้งหมด</button></div></div><DeskGrid room={room} onLock={(deskId,locked)=>manage(store.setDeskLock(room.id,deskId,locked))} onMoveStudent={(studentId,toDeskId)=>manage(store.moveStudent(room.id,studentId,toDeskId).then(()=>setNotice("ย้ายโต๊ะนักเรียนเรียบร้อยแล้ว")))}/><div className="legend"><span><i className="available"/>ว่าง</span><span><i className="occupied"/>มีคนนั่ง</span><span><i className="locked"/>ล็อกแล้ว</span></div></section><aside className="panel student-panel"><div className="section-title"><h2>นักเรียน ({room.students.length})</h2><button onClick={()=>router.push(`/teacher/classrooms/${room.id}/report`)}><Download/>รายงาน</button></div>{room.students.length===0?<div className="mini-empty"><QrCode/><strong>ยังไม่มีนักเรียน</strong><span>กด “แสดง QR” แล้วให้นักเรียนสแกน</span></div>:<div className="student-list">{room.students.map(s=><article key={s.id}><div className="student-name"><div><strong>{s.nickname}</strong><small>โต๊ะ {room.desks.find(d=>d.id===s.deskId)?.label??"ยังไม่เลือก"} · {s.totalScore} คะแนน</small></div></div>{s.handRaised&&<span className="hand-badge"><Hand/>ยกมือ</span>}<span>ข้อ {room.activity.levelIds.indexOf(s.currentLevel)+1}</span></article>)}</div>}</aside></div>
    <GameStartCountdown room={room} now={now}/>
    <RoomQrDialog roomName={room.name} open={qrOpen} onOpenChange={setQrOpen} roomCode={room.code} joinUrl={joinUrl}/>
    {configOpen&&<ActivityConfigDialog open={configOpen} onOpenChange={setConfigOpen} value={room.activity} catalogVersion={room.catalogVersion} onSave={activity=>manage(store.configureActivity(room.id,activity).then(()=>setNotice("บันทึกการตั้งค่าเกมแล้ว")))}/>}
  </main></AppShell>;
}
