"use client";
import { AppShell, LoadingState } from "@/components/app-shell";
import { Avatar } from "@/components/avatar";
import { DeskGrid } from "@/components/desk-grid";
import { currentStudentFrom, useDemo } from "@/lib/demo-store";
import { CirclePlay, Hand, Info, RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function StudentClassroom(){const store=useDemo();const router=useRouter();const{room,student}=currentStudentFrom(store);const[message,setMessage]=useState("");if(!store.ready)return <AppShell title="ห้องเรียน"><LoadingState/></AppShell>;if(!room||!student)return <AppShell title="ห้องเรียน"><main className="empty-state"><h1>เซสชันหมดอายุ</h1><p>ใส่รหัสห้องอีกครั้งเพื่อกลับเข้าห้อง</p><button className="primary-button" onClick={()=>router.push("/join")}>กลับไปเข้าห้อง</button></main></AppShell>;const desk=room.desks.find(d=>d.id===student.deskId);const canPlay=room.status==="RUNNING";return <AppShell title={room.name}><main className="classroom-shell student-view"><section className="student-welcome panel"><Avatar value={student.avatar}/><div><p className="eyebrow">เข้าห้องแล้ว</p><h1>สวัสดี {student.nickname}</h1><p>{room.name} · รหัส {room.code}</p></div><button className={student.handRaised?"hand-button raised":"hand-button"} onClick={store.toggleHand}><Hand/>{student.handRaised?"เอามือลง":"ยกมือ"}</button></section>{message&&<div className={message.includes("เรียบร้อย")?"success-box":"error-box"} role="status">{message}</div>}<section className="panel"><div className="section-title"><div><h2>{student.deskId?"เปลี่ยนที่นั่ง":"เลือกที่นั่ง"}</h2><span>{desk?.locked?"คุณครูล็อกโต๊ะนี้แล้ว":"โต๊ะที่เลือกจะยังไม่ล็อกจนกว่าครูจะสั่ง"}</span></div><span className="step-pill">ขั้นตอนที่ 2 จาก 2</span></div><DeskGrid room={room} selectedId={student.deskId} onSelect={id=>{const r=store.selectDesk(id);setMessage(r.message)}}/></section><section className={`waiting-strip ${canPlay?"ready":""}`}><div>{canPlay?<CirclePlay/>:<RefreshCw/>}<span><strong>{canPlay?"คุณครูเริ่มกิจกรรมแล้ว":"กำลังรอคุณครูเริ่มกิจกรรม"}</strong><small>{canPlay?"เข้าสู่ห้องทดลองและเริ่มด่านแรกได้เลย":"หน้านี้จะอัปเดตเมื่อสถานะห้องเปลี่ยน"}</small></span></div><button className="primary-button compact" disabled={!canPlay||!student.deskId} onClick={()=>router.push("/student/lab")}>เข้าห้องทดลอง</button></section><p className="inline-note"><Info/>หากอินเทอร์เน็ตขาดหาย ระบบจะโหลดสถานะล่าสุดกลับมาเมื่อเชื่อมต่ออีกครั้ง</p></main></AppShell>}
