"use client";
import { AppShell, LoadingState, StepIndicator } from "@/components/app-shell";
import { Avatar } from "@/components/avatar";
import { DeskGrid } from "@/components/desk-grid";
import { GameStartCountdown, useGameClock } from "@/components/game-start-countdown";
import { currentStudentFrom, useDemo } from "@/lib/demo-store";
import { gameIsLive } from "@/lib/live-game";
import { CirclePlay, Hand, Info, RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export default function StudentClassroom(){const store=useDemo();const router=useRouter();const{room,student}=currentStudentFrom(store);const[message,setMessage]=useState("");const now=useGameClock(room);const startAt=room?.gameStartsAt;const roomId=room?.id;const readyToPlay=!!room&&!!student?.deskId&&gameIsLive(room,now);
  useEffect(()=>{if(!readyToPlay||!roomId||!startAt)return;const key=`chemclass-started-${roomId}-${startAt}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,"1");router.replace("/student/lab")},[readyToPlay,roomId,startAt,router]);
  if(!store.ready)return <AppShell title="ห้องเรียน"><LoadingState/></AppShell>;if(!room||!student)return <AppShell title="ห้องเรียน"><main className="empty-state"><h1>เซสชันหมดอายุ</h1><p>สแกน QR อีกครั้งเพื่อกลับเข้าห้อง</p><button className="primary-button" onClick={()=>router.push("/join")}>กลับไปเข้าห้อง</button></main></AppShell>;const desk=room.desks.find(d=>d.id===student.deskId);const canPlay=gameIsLive(room,now);const ready=canPlay&&!!student.deskId;return <AppShell title={room.name} back="/student/avatar"><main className="classroom-shell student-view"><StepIndicator current={3} items={["เข้าห้อง","สร้างตัวละคร","เลือกที่นั่ง"]}/><section className="student-welcome panel"><Avatar value={student.avatar}/><div><p className="eyebrow">เข้าห้องแล้ว</p><h1>สวัสดี {student.nickname}</h1><p>{room.name} · รหัส {room.code}</p></div><button className={student.handRaised?"hand-button raised":"hand-button"} aria-pressed={student.handRaised} onClick={async()=>{try{await store.toggleHand();setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"ยกมือไม่ได้")}}}><Hand/>{student.handRaised?"เอามือลง":"ยกมือถามครู"}</button></section>{message&&<div className={message.includes("เรียบร้อย")?"success-box":"error-box"} role="status">{message}</div>}<section className="panel seat-panel"><div className="section-title"><div><h2>{student.deskId?`ที่นั่งของฉัน: โต๊ะ ${desk?.label}`:"เลือกที่นั่งของคุณ"}</h2><span>{desk?.locked?"คุณครูล็อกที่นั่งนี้แล้ว คุณยังเล่นเกมได้ตามปกติ":"โต๊ะสีเขียวเลือกได้ และจะยังไม่ล็อกจนกว่าครูจะสั่ง"}</span></div>{student.deskId&&<span className="seat-confirmed"><CirclePlay/>เลือกแล้ว</span>}</div><DeskGrid room={room} selectedId={student.deskId} onSelect={async id=>{const r=await store.selectDesk(id);setMessage(r.message)}}/></section><section className={`waiting-strip ${ready?"ready":""}`}><div>{canPlay?<CirclePlay/>:<RefreshCw/>}<span><strong>{!student.deskId?"เลือกโต๊ะก่อนเริ่มทดลอง":room.status==="RUNNING"&&!canPlay?"เตรียมเริ่มเกม":canPlay?"ห้องทดลองพร้อมแล้ว":"กำลังรอคุณครูเริ่มกิจกรรม"}</strong><small>{!student.deskId?"แตะโต๊ะว่างด้านบน":canPlay?"กำลังพาเข้าสู่เกมอัตโนมัติ":"หน้านี้จะอัปเดตเมื่อสถานะห้องเปลี่ยน"}</small></span></div><button className="primary-button compact" disabled={!ready} onClick={()=>router.push("/student/lab")}>เข้าห้องทดลอง</button></section><p className="inline-note"><Info/>หากอินเทอร์เน็ตขาดหาย ระบบจะโหลดสถานะล่าสุดกลับมาเมื่อเชื่อมต่ออีกครั้ง</p><GameStartCountdown room={room} now={now}/></main></AppShell>}
